/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Chelsey Claudia
 */
public class AdminFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminFrame.class.getName());

    /**
     * Creates new form AdminFrame
     */
    public AdminFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDashboard1 = new javax.swing.JLabel();
        lblDashboard = new javax.swing.JLabel();
        btnLogout = new javax.swing.JToggleButton();
        btnPerawatan = new javax.swing.JToggleButton();
        btnReservasi = new javax.swing.JToggleButton();
        btnDataHewan = new javax.swing.JToggleButton();
        btnDataPemilik = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDashboard1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblDashboard1.setText("Haloo Admin !");
        getContentPane().add(lblDashboard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));

        lblDashboard.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblDashboard.setForeground(new java.awt.Color(255, 255, 255));
        lblDashboard.setText("Dashboard Admin");
        getContentPane().add(lblDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 660, 100, 40));

        btnPerawatan.setBackground(new java.awt.Color(45, 40, 0));
        btnPerawatan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPerawatan.setForeground(new java.awt.Color(255, 255, 255));
        btnPerawatan.setText("Perawatan");
        btnPerawatan.addActionListener(this::btnPerawatanActionPerformed);
        getContentPane().add(btnPerawatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 420, 190, 80));

        btnReservasi.setBackground(new java.awt.Color(64, 50, 0));
        btnReservasi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnReservasi.setForeground(new java.awt.Color(255, 255, 255));
        btnReservasi.setText("Reservasi");
        btnReservasi.addActionListener(this::btnReservasiActionPerformed);
        getContentPane().add(btnReservasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 420, 190, 80));

        btnDataHewan.setBackground(new java.awt.Color(50, 43, 1));
        btnDataHewan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDataHewan.setForeground(new java.awt.Color(255, 255, 255));
        btnDataHewan.setText("Data Hewan");
        btnDataHewan.addActionListener(this::btnDataHewanActionPerformed);
        getContentPane().add(btnDataHewan, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 270, 190, 80));

        btnDataPemilik.setBackground(new java.awt.Color(69, 57, 0));
        btnDataPemilik.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDataPemilik.setForeground(new java.awt.Color(255, 255, 255));
        btnDataPemilik.setText("Data Pemilik");
        btnDataPemilik.addActionListener(this::btnDataPemilikActionPerformed);
        getContentPane().add(btnDataPemilik, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 190, 80));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Penitipan Hewan");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sistem");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDataPemilikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataPemilikActionPerformed
     new DataPemilikFrame().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_btnDataPemilikActionPerformed

    private void btnDataHewanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataHewanActionPerformed
     new DataHewanFrame().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_btnDataHewanActionPerformed

    private void btnReservasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservasiActionPerformed
     new ReservasiFrame().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_btnReservasiActionPerformed

    private void btnPerawatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerawatanActionPerformed
     new PerawatanFrame().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_btnPerawatanActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
     new LoginFrame().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnDataHewan;
    private javax.swing.JToggleButton btnDataPemilik;
    private javax.swing.JToggleButton btnLogout;
    private javax.swing.JToggleButton btnPerawatan;
    private javax.swing.JToggleButton btnReservasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblDashboard1;
    // End of variables declaration//GEN-END:variables
}
