/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import config.Koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Chelsey Claudia
 */
public class DataHewanFrame extends javax.swing.JFrame {
    private String idHewan = "";
    private ArrayList<Integer> idPemilikList = new ArrayList<>();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DataHewanFrame.class.getName());

    private void loadPemilik() {
    cmbPemilik.removeAllItems();
    idPemilikList.clear();

    try {
        Connection conn = Koneksi.getConnection();

        String sql = "SELECT id_akun, nama_lengkap FROM akun WHERE role = 'pemilik'";
        PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            idPemilikList.add(rs.getInt("id_akun"));
            cmbPemilik.addItem(rs.getString("nama_lengkap"));
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat data pemilik: " + e.getMessage());
    }
}
    
    private void isiJenisHewan() {
    cmbJenisHewan.removeAllItems();
    cmbJenisHewan.addItem("Kucing");
    cmbJenisHewan.addItem("Anjing");
    cmbJenisHewan.addItem("Kelinci");
}
    
    private void tampilData() {
    DefaultTableModel model = new DefaultTableModel();

    model.addColumn("ID Hewan");
    model.addColumn("ID Pemilik");
    model.addColumn("Pemilik");
    model.addColumn("Nama Hewan");
    model.addColumn("Jenis Hewan");
    model.addColumn("Umur");
    model.addColumn("Catatan");

    try {
        Connection conn = Koneksi.getConnection();

        String sql = "SELECT hewan.id_hewan, hewan.id_pemilik, akun.nama_lengkap, "
                   + "hewan.nama_hewan, hewan.jenis_hewan, hewan.umur, hewan.catatan "
                   + "FROM hewan "
                   + "LEFT JOIN akun ON hewan.id_pemilik = akun.id_akun";

        PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("id_hewan"),
                rs.getInt("id_pemilik"),
                rs.getString("nama_lengkap"),
                rs.getString("nama_hewan"),
                rs.getString("jenis_hewan"),
                rs.getInt("umur"),
                rs.getString("catatan")
            });
        }

        tblHewan.setModel(model);

        // sembunyikan kolom ID Pemilik agar tampilan lebih rapi
        tblHewan.getColumnModel().getColumn(1).setMinWidth(0);
        tblHewan.getColumnModel().getColumn(1).setMaxWidth(0);
        tblHewan.getColumnModel().getColumn(1).setWidth(0);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal menampilkan data hewan: " + e.getMessage());
    }
}
    
    private void kosongkanForm() {
    idHewan = "";

    if (cmbPemilik.getItemCount() > 0) {
        cmbPemilik.setSelectedIndex(0);
    }

    if (cmbJenisHewan.getItemCount() > 0) {
        cmbJenisHewan.setSelectedIndex(0);
    }

    txtNamaHewan.setText("");
    txtUmur.setText("");
    txtCatatan.setText("");
}
    
    /**
     * Creates new form DataHewanFrame
     */
    
    public DataHewanFrame() {
    initComponents();
    loadPemilik();
    isiJenisHewan();
    tampilData();
    setLocationRelativeTo(null);
}
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        txtCatatan = new javax.swing.JTextArea();
        btnTambah = new javax.swing.JToggleButton();
        btnReset = new javax.swing.JToggleButton();
        btnKembali = new javax.swing.JToggleButton();
        btnEdit = new javax.swing.JToggleButton();
        txtUmur = new javax.swing.JTextField();
        txtNamaHewan = new javax.swing.JTextField();
        cmbJenisHewan = new javax.swing.JComboBox<>();
        btnLogout = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHewan = new javax.swing.JTable();
        btnHapus1 = new javax.swing.JToggleButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbPemilik = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCatatan.setColumns(20);
        txtCatatan.setRows(5);
        jScrollPane2.setViewportView(txtCatatan);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 160, 260, 140));

        btnTambah.setForeground(new java.awt.Color(51, 51, 0));
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(this::btnTambahActionPerformed);
        getContentPane().add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 90, -1));

        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 390, 90, -1));

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(this::btnKembaliActionPerformed);
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 390, 90, -1));

        btnEdit.setText("Edit");
        btnEdit.addActionListener(this::btnEditActionPerformed);
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 90, -1));

        txtUmur.addActionListener(this::txtUmurActionPerformed);
        getContentPane().add(txtUmur, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 230, 30));
        getContentPane().add(txtNamaHewan, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 230, 30));

        cmbJenisHewan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anjing", "Kucing", "Kelinci" }));
        cmbJenisHewan.addActionListener(this::cmbJenisHewanActionPerformed);
        getContentPane().add(cmbJenisHewan, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 230, 30));

        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 80, 110, -1));

        tblHewan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Hewan", "Pemilik", "Nama Hewan", "Jenis Hewan", "Umur (tahun)", "Catatan"
            }
        ));
        tblHewan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHewanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHewan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 427, 830, 270));

        btnHapus1.setText("Hapus");
        btnHapus1.addActionListener(this::btnHapus1ActionPerformed);
        getContentPane().add(btnHapus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 390, 90, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel12.setText("Catatan");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 160, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel11.setText("Pemilik");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel10.setText("Jenis Hewan");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel9.setText("Nama Hewan");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setText("Form Data Hewan");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Penitipan Hewan");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sistem");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 70, -1));

        cmbPemilik.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPemilik.addActionListener(this::cmbPemilikActionPerformed);
        getContentPane().add(cmbPemilik, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 230, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel13.setText("Umur (tahun)");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg1.png"))); // NOI18N
        jLabel1.setText("ppp");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1361, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void cmbJenisHewanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbJenisHewanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbJenisHewanActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
    try {
        if (idHewan.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih data hewan yang ingin diedit!");
            return;
        }

        if (cmbPemilik.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Data pemilik belum tersedia!");
            return;
        }

        String namaHewan = txtNamaHewan.getText();
        String jenisHewan = cmbJenisHewan.getSelectedItem().toString();
        String umurText = txtUmur.getText();
        String catatan = txtCatatan.getText();

        if (namaHewan.isEmpty() || umurText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama hewan dan umur harus diisi!");
            return;
        }

        int indexPemilik = cmbPemilik.getSelectedIndex();
        int idPemilik = idPemilikList.get(indexPemilik);
        int umur = Integer.parseInt(umurText);

        Connection conn = Koneksi.getConnection();

        String sql = "UPDATE hewan SET id_pemilik = ?, nama_hewan = ?, jenis_hewan = ?, "
                   + "umur = ?, catatan = ? WHERE id_hewan = ?";

        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setInt(1, idPemilik);
        pst.setString(2, namaHewan);
        pst.setString(3, jenisHewan);
        pst.setInt(4, umur);
        pst.setString(5, catatan);
        pst.setString(6, idHewan);

        pst.executeUpdate();

        JOptionPane.showMessageDialog(this, "Data hewan berhasil diedit.");

        tampilData();
        kosongkanForm();

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Umur harus berupa angka!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal mengedit data hewan: " + e.getMessage());
    }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
    new AdminFrame().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
    kosongkanForm();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnHapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapus1ActionPerformed
    try {
        if (idHewan.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih data hewan yang ingin dihapus!");
            return;
        }

        int konfirmasi = JOptionPane.showConfirmDialog(
            this,
            "Yakin ingin menghapus data hewan ini?",
            "Konfirmasi Hapus",
            JOptionPane.YES_NO_OPTION
        );

        if (konfirmasi == JOptionPane.YES_OPTION) {
            Connection conn = Koneksi.getConnection();

            String sql = "DELETE FROM hewan WHERE id_hewan = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, idHewan);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Data hewan berhasil dihapus.");

            tampilData();
            kosongkanForm();
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal menghapus data hewan: " + e.getMessage());
    }
    }//GEN-LAST:event_btnHapus1ActionPerformed

    private void txtUmurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUmurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUmurActionPerformed

    private void cmbPemilikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPemilikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPemilikActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
    try {
        if (cmbPemilik.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Data pemilik belum tersedia!");
            return;
        }

        String namaHewan = txtNamaHewan.getText();
        String jenisHewan = cmbJenisHewan.getSelectedItem().toString();
        String umurText = txtUmur.getText();
        String catatan = txtCatatan.getText();

        if (namaHewan.isEmpty() || umurText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama hewan dan umur harus diisi!");
            return;
        }

        int indexPemilik = cmbPemilik.getSelectedIndex();
        int idPemilik = idPemilikList.get(indexPemilik);
        int umur = Integer.parseInt(umurText);

        Connection conn = Koneksi.getConnection();

        String sql = "INSERT INTO hewan (id_pemilik, nama_hewan, jenis_hewan, umur, catatan) "
                   + "VALUES (?, ?, ?, ?, ?)";

        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setInt(1, idPemilik);
        pst.setString(2, namaHewan);
        pst.setString(3, jenisHewan);
        pst.setInt(4, umur);
        pst.setString(5, catatan);

        pst.executeUpdate();

        JOptionPane.showMessageDialog(this, "Data hewan berhasil ditambahkan.");

        tampilData();
        kosongkanForm();

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Umur harus berupa angka!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal menambah data hewan: " + e.getMessage());
    }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void tblHewanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHewanMouseClicked
 int baris = tblHewan.getSelectedRow();

    idHewan = tblHewan.getValueAt(baris, 0).toString();

    String idPemilikTabel = tblHewan.getValueAt(baris, 1).toString();

    for (int i = 0; i < idPemilikList.size(); i++) {
        if (idPemilikList.get(i).toString().equals(idPemilikTabel)) {
            cmbPemilik.setSelectedIndex(i);
            break;
        }
    }

    txtNamaHewan.setText(tblHewan.getValueAt(baris, 3).toString());
    cmbJenisHewan.setSelectedItem(tblHewan.getValueAt(baris, 4).toString());
    txtUmur.setText(tblHewan.getValueAt(baris, 5).toString());
    txtCatatan.setText(tblHewan.getValueAt(baris, 6).toString());
    }//GEN-LAST:event_tblHewanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DataHewanFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnEdit;
    private javax.swing.JToggleButton btnHapus1;
    private javax.swing.JToggleButton btnKembali;
    private javax.swing.JToggleButton btnLogout;
    private javax.swing.JToggleButton btnReset;
    private javax.swing.JToggleButton btnTambah;
    private javax.swing.JComboBox<String> cmbJenisHewan;
    private javax.swing.JComboBox<String> cmbPemilik;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblHewan;
    private javax.swing.JTextArea txtCatatan;
    private javax.swing.JTextField txtNamaHewan;
    private javax.swing.JTextField txtUmur;
    // End of variables declaration//GEN-END:variables
}
