/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Chelsey Claudia
 */
public class UserFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserFrame.class.getName());

    /**
     * Creates new form UserFrame
     */
    public UserFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogout = new javax.swing.JToggleButton();
        btnLihatPerawatan = new javax.swing.JToggleButton();
        btnLihatReservasi = new javax.swing.JToggleButton();
        btnLihatHewan = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogout.setBackground(new java.awt.Color(255, 0, 0));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 670, 110, -1));

        btnLihatPerawatan.setBackground(new java.awt.Color(45, 42, 1));
        btnLihatPerawatan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLihatPerawatan.setForeground(new java.awt.Color(255, 255, 255));
        btnLihatPerawatan.setText("Lihat Data Perawatan");
        btnLihatPerawatan.addActionListener(this::btnLihatPerawatanActionPerformed);
        getContentPane().add(btnLihatPerawatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 400, 220, 50));

        btnLihatReservasi.setBackground(new java.awt.Color(43, 38, 0));
        btnLihatReservasi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLihatReservasi.setForeground(new java.awt.Color(255, 255, 255));
        btnLihatReservasi.setText("Lihat Data Reservasi");
        btnLihatReservasi.addActionListener(this::btnLihatReservasiActionPerformed);
        getContentPane().add(btnLihatReservasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 310, 210, 50));

        btnLihatHewan.setBackground(new java.awt.Color(48, 35, 1));
        btnLihatHewan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLihatHewan.setForeground(new java.awt.Color(255, 255, 255));
        btnLihatHewan.setText("Lihat Data Hewan");
        btnLihatHewan.addActionListener(this::btnLihatHewanActionPerformed);
        getContentPane().add(btnLihatHewan, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 210, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setText("Dashboard Pemilik");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Kami akan selalu memberikan yang terbaik!");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 550, -1, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Sistem");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Penitipan Hewan");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 230, -1, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Terima kasih telah mempercayakan hewan kesayangan anda kepada kami.");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 510, -1, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Stiker3.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 530, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-64, 0, 1450, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLihatHewanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatHewanActionPerformed
    new LihatHewanFrame().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnLihatHewanActionPerformed

    private void btnLihatPerawatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatPerawatanActionPerformed
    new LihatPerawatanFrame().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnLihatPerawatanActionPerformed

    private void btnLihatReservasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatReservasiActionPerformed
    new LihatReservasiFrame().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnLihatReservasiActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
    new LoginFrame().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UserFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnLihatHewan;
    private javax.swing.JToggleButton btnLihatPerawatan;
    private javax.swing.JToggleButton btnLihatReservasi;
    private javax.swing.JToggleButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
